# Generated by Django 5.1.3 on 2024-12-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the image', max_length=200)),
                ('image', models.ImageField(help_text='Upload an image', upload_to='gallery/')),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
