# Generated by Django 5.1.3 on 2025-01-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='job_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default='Not Provided', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
